import discord
from _typeshed import Incomplete
from watchdog.events import FileSystemEventHandler

formatting: Incomplete
log: Incomplete
loggingFileData: Incomplete
bot: Incomplete
observer: Incomplete
cog_log: Incomplete

class FileHandler(FileSystemEventHandler):
    def on_modified(self, event) -> None: ...

def get_git_revision_short_hash() -> str: ...
def get_version(): ...
async def on_ready() -> None: ...
async def on_disconnect() -> None: ...
async def on_connect() -> None: ...
async def on_message(message: discord.Message): ...
def handler(x, y) -> None: ...
async def main() -> None: ...
