from _typeshed import Incomplete
from discord.ext import commands

class Error_Handling(commands.Cog):
    bot: Incomplete
    log: Incomplete
    def __init__(self, bot: commands.Bot) -> None: ...
    def revision_long_hash(self) -> str: ...
    def revision_short_hash(self) -> str: ...
    async def on_command_error(self, ctx: commands.Context, error: Exception): ...

async def setup(bot: commands.Bot): ...
