from _typeshed import Incomplete
from discord.ext import commands

class Inventory_And_Shop(commands.Cog):
    bot: Incomplete
    def __init__(self, bot: commands.Bot) -> None: ...
    async def shop(self, ctx: commands.Context): ...
    async def buy(self, ctx: commands.Context, item: Items, amount: int): ...

async def setup(bot: commands.Bot): ...
