from _typeshed import Incomplete

logger: Incomplete

class Cards:
    cards: Incomplete
    suits: Incomplete
    cardInfo: Incomplete
    deck: Incomplete
    def __init__(self) -> None: ...
    def shuffle_cards(self, *, nUnique: bool = ..., sUnique: bool = ...): ...
    def Draw_Card(self): ...
    def Get_Deck_Card(self, index: int): ...
    def Check_If_Higher(self, card, newCard): ...
