import typing

def load_bank() -> None: ...

class FileHandler:
    def __init__(self) -> None: ...
    async def SaveFile(self, name: str, data) -> None: ...
    def serializer(self, obj) -> typing.Any: ...
    async def ReadFile(self, name: str) -> dict: ...
