from _typeshed import Incomplete

class plural:
    value: Incomplete
    def __init__(self, value) -> None: ...
    def __format__(self, format_spec): ...

def human_join(seq, delim: str = ..., final: str = ...): ...

class TabularData:
    def __init__(self) -> None: ...
    def set_columns(self, columns) -> None: ...
    def add_row(self, row) -> None: ...
    def add_rows(self, rows) -> None: ...
    def render(self): ...

def format_dt(dt, style: Incomplete | None = ...): ...
