import discord
from _typeshed import Incomplete
from src.utils import uis as uis
from src.utils.MoneySelector import MoneySelector as MoneySelector

logger: Incomplete

class Multiplayer:
    Interaction: Incomplete
    owner: Incomplete
    limit: Incomplete
    data: Incomplete
    game: Incomplete
    callbackFunc: Incomplete
    def __init__(self, Interaction: discord.Interaction, name: str, limit: int = ...) -> None: ...
    async def MoneyCallback(self, value: int, user: discord.Member): ...
    async def skipCallback(self, value: int, user: discord.Member): ...
    async def AskCallback(self, Interaction: discord.Interaction, label: str): ...
    async def Ask(self) -> None: ...
    async def AcceptInvitation(self, Interaction: discord.Interaction, label: str): ...
    buttonView: Incomplete
    InviteMsg: Incomplete
    async def Invite(self, Interaction: discord.Interaction, label: str): ...
    async def defaultCallback(self, Interaction: discord.Interaction, value): ...
    async def callback(self, value: int = ...): ...
    async def start(self, callback: Incomplete | None = ...) -> None: ...
