import discord
from _typeshed import Incomplete
from discord.ext import commands as commands
from src.utils import (
    MoneySelector as MoneySelector,
    bank as bank,
    game_template as game_template,
    uis as uis,
)

class GuessNumber(game_template.Template):
    bot: Incomplete
    bet: int
    interaction: Incomplete
    account: Incomplete
    confirmed: bool
    def __init__(self, bot: commands.Bot) -> None: ...
    async def callback_money(self, value: int, user): ...
    async def easy(self, interaction: discord.Interaction, label: str): ...
    async def medium(self, interaction: discord.Interaction, label: str): ...
    async def hard(self, interaction: discord.Interaction, label: str): ...
    async def impossible(self, interaction: discord.Interaction, label: str): ...
    async def confirmation_yes(self, interaction: discord.Interaction, label: str): ...
    async def confirmation_no(self, interaction: discord.Interaction, label: str): ...
    mapped: Incomplete
    number: Incomplete
    guesses: int
    answer: Incomplete
    range: Incomplete
    async def start_game(self, range: int, interaction: discord.Interaction): ...
    async def actually_starting_the_game_with_rapid_pace_on_god(self) -> None: ...
    async def start(self, interaction: discord.Interaction): ...
    @property
    def display_emoji(self): ...

def game_setup(bot: commands.Bot): ...
